name: Sync to SDK Repository

on:
  push:
    paths:
    - 'typed_contracts/**'
    - 'constants/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2

    - name: Push to destination repo
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        git clone https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/henrypalacios/xsigners-sdk.git xsigners_sdk 
        cp -r typed_contracts xsigners_sdk/src/
        cp -r constants xsigners_sdk/src/
        
        cd xsigners_sdk 
        git add .
        git commit -m "Sync from source repo"
        git push

